name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update README
        run: |
          # Define a list of URLs
          URLS=("https://media4.giphy.com/media/IThjAlJnD9WNO/giphy.gif?cid=ecf05e47"
                "https://media4.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif"
                "https://media4.giphy.com/media/3o7aD2saalBwwftBIY/giphy.gif"
                "https://media4.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif"
                "https://media4.giphy.com/media/13CoXDiaCcCoyk/giphy.gif")

          # Select a random URL
          RANDOM_URL=${URLS[$RANDOM % ${#URLS[@]}]}

          # Update the placeholder in the README template
          sed "s|PLACEHOLDER_SRC|$RANDOM_URL|" README_dyluc.md > updated_README.md

      - name: Commit and Push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git clone https://${GH_TOKEN}@github.com/dyluc/scheduler.git
          cp updated_README.md scheduler/README.md
          cd scheduler
          git config --local user.email "dylanlucas1510@gmail.com"
          git config --local user.name "Commit-sapien"
          git add README.md
          git commit -m "Daily README update [skip ci]" || echo "Nothing to commit"

          # Push the integrated changes
          git push origin master
