name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update README
        run: |
          # Define a list of URLs
          URLS=("https://fonts.gstatic.com/s/e/notoemoji/latest/1f422/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f40d/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f40a/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f438/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f996/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f995/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f409/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f98e/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f400/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f416/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f410/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f998/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f412/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f9a7/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f9a6/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f426/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f426_200d_2b1b/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f985/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f9ad/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f421/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f433/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f419/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f980/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1fabc/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f577_fe0f/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f40c/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f41c/512.gif"
                "https://fonts.gstatic.com/s/e/notoemoji/latest/1f41d/512.gif")

          # Select a random URL
          RANDOM_URL=${URLS[$RANDOM % ${#URLS[@]}]}

          # Update the placeholder in the README template
          sed "s|PLACEHOLDER_SRC|$RANDOM_URL|" README_dyluc.md > updated_README.md

      - name: Commit and Push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git clone https://${GH_TOKEN}@github.com/dyluc/dyluc.git
          cp updated_README.md dyluc/README.md
          cd dyluc
          git config --local user.name "Commit-sapien"
          git add README.md
          git commit -m "Daily README update [skip ci]" || echo "Nothing to commit"

          # Push the integrated changes
          git push origin master
